---
title: "Rをつかってみよう"
author: "伊東宏樹"
format: revealjs
editor: visual
---

## 本日の内容

::: nonincremental
-   Rとは?

-   RStudio

-   パッケージの利用

-   基本的な使い方

-   Tidyなデータとデータ処理

-   グラフ作成
:::

## 自己紹介

-   氏名: 伊東宏樹

-   個人事業主（[伊東生態統計研究室](https://ito4303.sakura.ne.jp/)）

    -   データ解析、執筆・翻訳、研修講師などお引き受けいたします。

-   出版物: 『[BUGSで学ぶ階層モデリング入門](https://www.kyoritsu-pub.co.jp/book/b10003729.html)』『[生態学のための階層モデリング](https://www.kyoritsu-pub.co.jp/book/b10003301.html)』（以上共訳）など

## Rとは?

-   [統計計算とグラフィックスのためのシステム](https://cran.r-project.org/doc/FAQ/R-FAQ.html#What-is-R_003f)（言語と環境）

-   オープンソース

-   無料でつかえる

-   豊富なパッケージ（後述）で機能を追加できる

## インストール

-   CRANからインストーラーをダウンロード

    -   ミラー

        -   日本 <https://ftp.yz.yamagata-u.ac.jp/pub/cran/>

        -   クラウド <https://cloud.r-project.org/>

-   各種パッケージシステム（homebrew, winget, ...）からもインストールできる

## RStudio

-   Posit社が開発している統合開発環境（IDE）

-   <https://posit.co/download/rstudio-desktop/>

-   設定

    -   ペーン

-   基本的な使用法

-   プロジェクト

## GUI環境

Rをエンジンとして使用するGUI環境もあり

-   R Commander ([Rcmdr](https://cran.r-project.org/package=Rcmdr)パッケージ)
-   [jamovi](https://www.jamovi.org)
-   [JASP](https://jasp-stats.org)
-   [Bluesky Statistics](https://www.blueskystatistics.com)

手作業ではエラーしがち → Rスクリプトを保存しておくとよい

## パッケージの利用

-   特定の目的のための関数やデータなどをまとめたもの

-   CRANなどからインストールできる

-   マニアックな解析方法もたいていある

-   ユーザーが自分で作って公開できる

## 基本的な使い方

-   ヘルプ

<!-- -->

-   計算

    -   演算子
    -   基本的な統計関数

-   データの読み込み

    -   CSVファイル

    -   Excelファイル

## Tidyなデータとデータ処理

-   Tidy data（整然データ）

-   Tidyverse

    -   tidyverseパッケージ

## グラフの作成

-   デフォルトのグラフィック環境(base graphics)を使用する方法
-   ggplot2パッケージを使用する方法

## さらに知るには

-   地域コミュニティ

    -   Kanazawa.R, Tokyo.R, ...

-   r-wakalang
